### ISSUE TITLE
default audio output should be first in the enumerateDevice returned list

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-output#113]
Following microphones and cameras, we should try exposing the default audio output device using its first position.
This also probably means it should always be exposed since '' allows to be used by setSinkId.

In case of change of default audio output device, we might also want to fire a devicechange event if more than one audio output device has been exposed.

**Comment by guidou** [comment]
I agree with this. Also, this all matches Chromium's behavior.

**Comment by guest271314** [comment]
`enumerateDevices()` currently returns inconsistent results re selecting and listing default devices https://github.com/w3c/mediacapture-main/issues/727. Would suggest to fix fix that inconsistency. Also, there really is no "default audio output device" https://github.com/w3c/mediacapture-output/issues/111  in either this or Media Capture an Streams main, at best there is a _re-routing_ of audio input device.

**Comment by guidou** [comment]
Since enumerateDevices is defined in mediacapture-main, I filed a https://github.com/w3c/mediacapture-main/issues/756 to track it there and closing this one.
