### ISSUE TITLE
default audio output should be first in the enumerateDevice returned list

### ISSUE THREAD

**Issue by guidou** [w3c/mediacapture-output#124]
The spec already mandates that the default microphone and the default camera (if they exist) should be the first devices listed in enumerateDevices. This should also apply to speakers.

This bug is basically the same as https://github.com/w3c/mediacapture-output/issues/113, but I filed it here because enumerateDevices is defined in this spec.

**Comment by jan-ivar** [comment]
I'm not sure it makes sense to keep this open, since we have no good way of writing automated WPT tests that require multiple devices. AFAIK there's no equivalent issue open for cams/mics being first, so I think we can close this.
