### ISSUE TITLE
HTMLMediaElement.setSinkId() when media element is paused doesn't change output device?

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-output#16]
http://w3c.github.io/mediacapture-output/#widl-HTMLMediaElement-setSinkId-Promise-void--DOMString-sinkId

The "stop playing this object's audio out of the device represented by the sinkId attribute" and "start playing this object's audio out of the device represented by sinkId" steps are predicated on the media element being playing.

A literal reading of this would be that calling `setSinkId()` while the media element is paused would have no effect other than changing the sinkId attribute, so that when playback continues it's using the original device.

Making these steps unconditional ought to fix the problem.

**Comment by martinthomson** [comment]
I think that this is fixed in the current version.  @foolip, @juberti, can this be closed?

**Comment by foolip** [comment]
No, it doesn't look like this has been fixed, it still says "If the media element's paused attribute is false, stop playing this object's audio out of the device represented by the sinkId attribute."

**Comment by juberti** [comment]
I don't think these steps can be unconditional. Clearly if the media is not playing out, you can't make it stop playing out. 

Perhaps we just need some text that says "set the underlying output device to X" that can be referenced regardless of whether paused is true or not.

**Comment by foolip** [comment]
Yeah, at some point there must be some spec language involving "the device represented by sinkId" that is run either when paused or when playback continues.

Notably, nothing in the WIP implementation at https://codereview.chromium.org/1128933008/ depends on the paused state of the media element.
