### ISSUE TITLE
Use deviceId instead of sinkId

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-output#17]
Using `deviceId` in all the different places would make this consistent with the `getUserMedia` spec and make it more obvious that these are the same thing that we're talking about.

**Comment by foolip** [comment]
There is an [Intent to Ship](https://groups.google.com/a/chromium.org/d/msg/blink-dev/ELz4SxMwa0U/CWsWMGjfCwAJ) this API on blink-dev. This kind of naming issue really must be resolved before anyone ships.

**Comment by alvestrand** [comment]
Not sure it makes sense to harmonize.
We can work from the theory that a sink ID is a device ID that identifies an output device. Using a camera's or microphone's ID in these places would not work.

In the particular case of media elements, it's got "src" and "srcObject" - I think that having a "sink" attribute is kind of natural. Calling the attribute "deviceid" would be confusing.

**Comment by foolip** [comment]
> Using a camera's or microphone's ID in these places would not work.

That's a very relevant distinction. Looks like @juberti has closed all issues on this repo so far, can you close this too if there's no implementor interest in changing this?

**Comment by juberti** [comment]
Closing per discussion.
