### ISSUE TITLE
Reserved words for device identifiers don't need 'id-'

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-output#18]
...prefix.  I believe that the intent of this prefix is to carve out some of the device identifier space for use in this specification.  That's unnecessary, though it might make sense to ensure that you only use reserved values that are shorter than the minimum size of an identifier.

As specified, this doesn't avoid the potential for collision. Assuming that an implementation is assigning identifiers while ignorant of this specification, then an implementation might assign one of these identifiers if they use the URL and filename safe variant of base64 to encode identifiers.  At 17 characters in length, `id-communications` is long enough to collide with a 102/104-bit value, which is a plausible amount of entropy, if a mite odd.

**Comment by alvestrand** [comment]
When I looked at this last, I thought the spec should reserve something - for instance, forbid the use of "id-" at the beginning of the string. Then again, I don't like the use of predefined values.
