### ISSUE TITLE
Problems with authorization for the output-only case

### ISSUE THREAD

**Issue by juberti** [w3c/mediacapture-output#2]
from Philippe Joseph Cohen:

The issue in the current proposal is that EnumerateDevice returns opaque information before user authorisation as current drafted in the EnumerateDevices specs. So with this opaque information and  without the the more meaningful properties (currently the ‘label’ one), apps won’t be in a position to decide if to prompt the user for authorisation to use a specific device based on just the opaque deviceId.

This implies that any authorization prompt must be for all devices (i.e. "web site X wants to enumerate your audio devices", as opposed to "web site X wants to access device Y").

**Comment by philjoseph** [comment]
I wonder if we have reached a decision on this issue. To strengthen my suggestion about using the terminology **sound output devices** see MacOSX, see 
![image](https://cloud.githubusercontent.com/assets/4303547/5891915/d0bb4868-a4b5-11e4-89c9-fedd138be63b.png)
Windows prefer sound playback but I am not convinced it's better.
