### ISSUE TITLE
Specify with what the setSinkId() promise should be rejected

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-output#24]
https://w3c.github.io/mediacapture-output/#widl-HTMLMediaElement-setSinkId-Promise-void--DOMString-sinkId

In step 5:
 1. Associate the audio output device represented by sinkId with this object for playout.
 2. If the preceding step failed, return a rejected promise.

Here it needs to be specified with what kind of exception the promise is rejected.

**Comment by foolip** [comment]
In the Chromium implementation, it looks like `SecurityError` and `AbortError` are both used in situations which could be fairly described as a failure of the "Associate the audio output device represented by sinkId with this object for playout" step.

**Comment by juberti** [comment]
Resolved by #25

**Comment by juberti** [comment]
er, #26
