### ISSUE TITLE
Specify action of id-communications when there is no communications device

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-output#30]
Copied from TAG review https://github.com/w3ctag/spec-reviews/issues/91

If there is no comms device, behavior should be predictable. I suggest that sound should go to the default device (same as "" or "id-multimedia").

**Comment by ShijunS** [comment]
Agree with @Alvestrand.  That will also be consistent with user experiences in Windows.

**Comment by alvestrand** [comment]
Seems obvious at TPAC. Please make it so.
