### ISSUE TITLE
CD publication of specification

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-output#37]
At the Lisbon TPAC meeting, we will raise the question of whether this spec is ready for publication as CD. Please add to this issue references to the issues that you think have to be resolved before CD publication.

Once all these are resolved, and we think review is adequate, we will ask for CD publication.

Harald, for the chairs.

**Comment by guidou** [comment]
I think we should resolve the issues related to the predefined IDs.
https://github.com/w3c/mediacapture-output/issues/30
https://github.com/w3c/mediacapture-output/issues/19
https://github.com/w3c/mediacapture-output/issues/18

One way is to deal with that is to just remove Section 4 from the spec.

**Comment by alvestrand** [comment]
Discussed at TPAC. Minutes: https://www.w3.org/2016/09/22-webrtc-minutes#item12

Decision not clear; I think we decided to live with predefined IDs, given that they have already shipped.
