### ISSUE TITLE
WG CR review for mediacapture-output

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-output#38]
This issue serves to track internal WG review (in the WGs making up the mediacapture TF) of the medacapture-output document for CR publication.
If you have reviewed the document, please add a “thumbs up” reaction to the issue.
If you find issues that you think need addressing before CR publication, please file the issue in Github and mention it in the comments.

The review lasts until Thursday, October 12, 2016. At that time, the chairs will decide whether or not the review result warrants asking the wider community to review the document for CR; if we do ask the wider community, a similar issue wil be filed for tracking that review.

**Comment by fluffy** [comment]
FWIW ...  I read it and did not see any blocking issues and this is ready for broader review. I think the hand wave "consent is implementation dependent" is sort of crap and we should do better but I don't expect any changes to that so don't plan to spend time on it.

**Comment by stefhak** [comment]
I also think it is ready for broader review (though we should probably get rid of the ```This is work in progress``` disclaimer in the section about WebAudio API extensions).
