### ISSUE TITLE
Sample rate can change when an `AudioContext` is running

### ISSUE THREAD

**Issue by padenot** [w3c/mediacapture-output#50]
> Requiring the sink ID to be set at construction time simplifies the implementation, since the output sample rate is fixed. 

Changing the sample-rate of a device while it is in use is something that can be done on all major desktop operating systems. This sentence implies that this is not the case.

I agree that it's hard to change the sample-rate of an `AudioContext`, but it's not hard to change it from a device to another, and should be supported.

Of course, in practice and if necessary, UAs will insert a resampler somewhere in the rendering pipeline so that the `AudioContext` can still render the audio at the original sample-rate, and everything will continue running smoothly.

**Comment by guidou** [comment]
>>  the sink ID to be set at construction time simplifies the implementation, since the output sample rate is fixed.

> Changing the sample-rate of a device while it is in use is something that can be done on all major desktop operating systems. This sentence implies that this is not the case.

No, it doesn't. The sentince in the spec implies that the implementation of AudioContext would be more complex.

> I agree that it's hard to change the sample-rate of an AudioContext, but it's not hard to change it from a device to another, and should be supported.

If it's hard to change the sample rate of an AudioContext, then it is at least as hard to switch the AudioContext from a device to another with a different sample rate. Switching to another device with the same sample rate would be simpler.

During the process of defining this spec we considered four different versions of the API (including a version that supported switching the device) and members of the team responsible for the Web Audio spec expressed their preference for not allowing changes to the device ID in order to avoid the resampling and jitter work necessary for this.

If the sample rate is changed at the OS level, this does not increase the implementation complexity for AudioContext since the resampling is handled outside of AudioContext.

**Comment by padenot** [comment]
> If it's hard to change the sample rate of an AudioContext, then it is at least as hard to switch the AudioContext from a device to another with a different sample rate. Switching to another device with the same sample rate would be simpler.
> 
> During the process of defining this spec we considered four different versions of the API (including a version that supported switching the device) and members of the team responsible for the Web Audio spec expressed their preference for not allowing changes to the device ID in order to avoid the resampling and jitter work necessary for this.

This is wrong and uninformed. It's very simple to do and has been implemented in Gecko, Blink, and I believe Edge for as long as there has been Web Audio API shipped on those implementations (with various degrees of success, Edge and Gecko get it right, Blink sometimes stops rendering audio). In fact, it's a necessary behaviour to implement the auto-device switching that authors expect (see #49). Get a browser and a laptop, plug in a USB headset, run a web audio application, hear the sound in the headset, unplug it, it continues playing on the speakers, re-plug it, it plays on the USB headset, etc. The same mechanism will happen under the hood if we allow authors to dynamically change the device of an `AudioContext`. 

Both technique are completely different in terms of implications and complexity.

- Changing the sample-rate of the `AudioContext` requires carefully changing a lot of state in the Web Audio graph, and informing authors that the sample-rate of the `AudioContext` has changed, because it's very possible that authors have based their code on a specific sample-rate, and their DSP pipeline makes it difficult to change the rate without glitching. Changing the sample-rate of an `AudioContext` is not something that we'll consider.
- Changing the audio device of a running `AudioContext` is simply a matter of pausing the graph for a short while, maybe (depending on if the old and new device have the same rate) inserting a resampler that converts to the rate of the old device (and thus probably the rate of the `AudioContext`) to the rate of the new device, or opening the device at the old rate (this is not always possible nor desirable, but is an implementation concern), and starting the audio stream on the new device, calling back into the `AudioContext` again. This is what you talk about in your last paragraph, the sample-rate change is not visible to the `AudioContext`, but happens somewhere anyways.
