### ISSUE TITLE
Mismatch between sinkId and deviceId names

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/mediacapture-output#57]
From [TAG review](https://github.com/w3ctag/spec-reviews/issues/132#issuecomment-256494694):
>  sinkId name doesn't seem to match-up with the property used to identify the output devices (deviceId) from MediaDeviceInfo

**Comment by guidou** [comment]
This was discussed in issue #17 and it was decided to keep sinkId.
The rationale is that a sink ID is a device ID that refers to an output device, so not all device IDs are usable as sink IDs.
