### ISSUE TITLE
Default value alias

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/mediacapture-output#60]
From [TAG review](https://github.com/w3ctag/spec-reviews/issues/132#issuecomment-256494694):
> Section 4's pre-defined Identifiers adds an alias to the empty string value with "id_multimedia". I wonder for clarity if this should just be the default value.

(probably over taken by events)

**Comment by guidou** [comment]
This issue was obsoleted by the removal of predefined IDs from this spec.
