### ISSUE TITLE
Add explainer document

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/mediacapture-output#61]
From [TAG review](https://github.com/w3ctag/spec-reviews/issues/132#issuecomment-257475407):
> we would really like to see an explainer document with some same code examples of use

**Comment by dontcallmedom** [comment]
@guidou is that something you're planning to develop (or already exists somewhere else)?

**Comment by guidou** [comment]
Yes, I'm planning to do this.
Can you point to a similar document for another spec to use as a guide?

**Comment by dontcallmedom** [comment]
e.g. https://github.com/w3c/ServiceWorker/blob/master/explainer.md

**Comment by dontcallmedom** [comment]
@guidou any progress / remaining interest on this?

**Comment by guidou** [comment]
I still have this in my queue, but there's always something of higher priority.
If someone else can do it sooner, I'll be happy to review.

**Comment by dontcallmedom** [comment]
Some input on the explainer:
https://github.com/w3ctag/design-reviews/issues/91#issuecomment-165236185
> As an aside, it's be great to see example code for this API somewhere so that folks can get a sense for how it hangs together with the rest of the system. The attribute/promise split for getter/setter might make a ton of sense, but it's hard to see. Same for the pre-defined devices list.

https://github.com/w3ctag/design-reviews/issues/91#issuecomment-165422127
> Example code can be found here: https://webrtc.github.io/samples/src/content/devices/multi/

**Comment by guidou** [comment]
closed by #67
