### ISSUE TITLE
Enumeration of output devices and permission model

### ISSUE THREAD

**Issue by aboba** [w3c/mediacapture-output#71]
I have recently gotten an inquiry from a developer attempting to utilize the [Audio Devices API](https://www.w3.org/TR/audio-output/) to select  an output audio device in a situation where there are no input devices (e.g. no microphone or camera).

To enumerate the output devices, they are calling `MediaDevices.enumerateDevices` to obtain `MediaDeviceInfo` relating to the devices and then once the user has selected an output device, `HTMLMediaElement.setSinkId(deviceId)` to set the output device.

Here is the catch. To provide the user with an intelligible list of output devices to select, the `label` attribute is needed.  As noted in Section 9.2.1 of [Media Capture and Streams](https://w3c.github.io/mediacapture-main/#access-control-model):

     The algorithm described above means that the access to media device information depends on 
     whether or not permission has been granted to the page's origin.

     If no such access has been granted, the MediaDeviceInfo dictionary will contain the deviceId, kind, 
     and groupId.

     If access has been granted for a media device, the MediaDeviceInfo dictionary will contain the 
    deviceId, kind, label, and groupId.

So the `label` attribute can only be obtained if permission has been granted. However, in a situation where there are no input devices, requesting access to the user's (non-existent) microphone and camera is problematic.

Was this interaction intentional?

**Comment by guidou** [comment]
This is certainly an issue in Chrome, but it's not clear to me that it's a spec bug.
In Chrome, the only way to get the permission is to call getUserMedia(), but nothing in the spec prevents setSinkId() from also being able to get the permission to use use devices.
Do you think we should change the spec to mandate that setSinkId() request permission?
Perhaps add a new function somewhere specifically to request permission?

**Comment by juberti** [comment]
This was discussed previously in #2; the consensus there was that we should have some way of obtaining device permissions separate from gUM, although it did not get into details. Not sure if we have a mechanism that could be easily used for this.

**Comment by alvestrand** [comment]
So the real question is "what API operation should be invoked in order to look at device names".
@jan-ivar has opinions; Mozilla is still arguing strongly against permissions.requestPermission().

**Comment by alvestrand** [comment]
One possibility (per @jan-ivar ) is to always allow output device labels.

**Comment by guidou** [comment]
If device labels are always allowed, what would be the point of having per-origin random device IDs?

**Comment by guidou** [comment]
Closing this issue since it refers more to an implementation bug than a spec bug.

**Comment by guidou** [comment]
Please reopen if you think this requires more discussion.
