### ISSUE TITLE
s/SecurityError/NotAllowedError/

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-output#74]
When we switched from `SecurityError` to `NotAllowedError` [two years ago](https://github.com/w3c/mediacapture-main/pull/331), we forgot this spec.

We should fix that for consistency with `getUserMedia`.

Also, we should tidy up the terminology by s/authorization/permission/ at the same time.

**Comment by guidou** [comment]
Fixed  by #75
