### ISSUE TITLE
Should setSinkId be functional in SecureContext only?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-output#78]
Following on https://github.com/w3c/webrtc-pc/issues/1945, would it make sense to make *setSinkId* `[SecureContext]`? I.e.
```js
console.log("setSinkId" in document.createElement('video')); // false in http
```
We're looking for guidance on implementing it in Firefox.

Currently, in Chrome this method exists in http, but is pretty much [useless](http://jsfiddle.net/jib1/Lumb0w6e/) (`SecurityError`).

As to the read-only `sinkId` attribute, we could leave it (`""`) or make it SecureContext as well (`undefined`). With no way to affect the attribute, it serves little purpose.

**Comment by guidou** [comment]
Making both [SecureContext] sgtm

**Comment by cynthia** [comment]
@alvestrand @dontcallmedom was this by any chance touched on during TPAC? If so, would love to see what the outcome of this was!

**Comment by jan-ivar** [comment]
@cynthia Yes, from [minutes](https://www.w3.org/2018/10/22-webrtc-minutes#item02) and recollection, both `setSinkId` and `sinkId` to be SecureContext only.

**Comment by jan-ivar** [comment]
Has PR.

**Comment by cynthia** [comment]
Since the PR has landed, would it make sense to close this?
