### ISSUE TITLE
setSinkId is inconsistent in handling of default value.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-output#79]
[sinkId](https://w3c.github.io/mediacapture-output/#dom-htmlmediaelement-sinkid) defaults to `""`(*"...the empty string if output is delivered through the user-agent default device"*)

But [[[SinkId]]](https://w3c.github.io/mediacapture-output/#htmlmediaelement-extensions) defaults to `null` (*"Let the element have a [[SinkId]] internal slot, initialized to null."*)

This messes up [setSinkId](https://w3c.github.io/mediacapture-output/#dom-htmlmediaelement-setsinkid) in observable ways:

 *"3. If sinkId is equal to element's [[SinkId]], return a promise resolved with undefined."*

```js
await element.setSinkId(element.sinkId); // NotFoundError
```

Instead, this should succeed, [like it does in Chrome](https://jsfiddle.net/jib1/Lumb0w6e/).

**Comment by guidou** [comment]
Fixed by #80
