### ISSUE TITLE
Normative reference to HTML 5.2 should be changed to HTML LS

### ISSUE THREAD

**Issue by svgeesus** [w3c/mediacapture-output#82]
The [normative references](https://w3c.github.io/mediacapture-output/#normative-references) lists HTML 5.x.

Since [W3C and WHAT WG signed the MOU](https://www.w3.org/2019/04/WHATWG-W3C-MOU.html), the HTML 5.2 reference should be changed to HTML LS in the bikeshed source.

**Comment by dontcallmedom** [comment]
This was done
