### ISSUE TITLE
Go back to the default output

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-output#85]
As long as the sinkId is not set, the sink is selected by the user agent.
There does not seem to be any way for a web page to go back to this original state.
Should we allow setSinkId('')?

**Comment by guidou** [comment]
Yes, we should. IIRC, setSinkId('') in Chromium switches to the default device.

**Comment by jan-ivar** [comment]
Closed by https://github.com/w3c/mediacapture-output/pull/95.
