### ISSUE TITLE
Behavior when device changes

### ISSUE THREAD

**Issue by achronop** [w3c/mediacapture-output#88]
I would like some clarifications regarding the described behavior when the device is unplugged and replugged. When a device is no longer available the spec states:

"if the media element's paused attribute is false when the device identified by the sinkId is no longer available, then playback will continue as normal. In this case, audio will not be rendered because the device to which the media element is attached is unavailable."

The way I perceive it is that we should not switch to another device. Instead, playback should continue without audio playing. Which means that we should continue advancing the position of the track but without having the audible result

I am testing Chrome's behavior and when the current output is removed it does switch to the system's default device. Is this because Chrome has not aligned with the spec yet?

Considering the following sample can anyone please clarify what is the expected behavior according to the spec?

```
element.srcObject = valid_media_stream;
element.play();
// sink2 is an external usb devive
element.setSinkId("sink2");
// wait a few seconds.
unplug sink2
// wait a few seconds.
replug sink2
```

**Comment by jan-ivar** [comment]
@alvestrand @guidou @henbos it looks like Chrome is not following the spec here. Can you speak to whether this is intentional, or whether you intend to align with the spec?

**Comment by achronop** [comment]
Any update on this?

**Comment by henbos** [comment]
@guidou can you comment?

**Comment by jan-ivar** [comment]
From meeting: @alvestrand mentioned that if you're e.g. in a library with headphones and 1000W external speakers, it might not be a great idea to switch to default output behind the app's back.

**Comment by jan-ivar** [comment]
I found https://bugs.chromium.org/p/chromium/issues/detail?id=506273

**Comment by jan-ivar** [comment]
I found https://bugs.chromium.org/p/chromium/issues/detail?id=697877

**Comment by achronop** [comment]
Thank you @jan-ivar . @guidou given the [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=697877) I assume that chrome's current behavior is not intended and you would like to align with the spec. Would you like to give me the way you perceive the description in the spec?

**Comment by dontcallmedom** [comment]
Closing since this is an implementation issue, not a spec issue (until proved otherwise)
