### ISSUE TITLE
Option to remove consent for default audio device?

### ISSUE THREAD

**Issue by svgeesus** [w3c/mediacapture-output#89]
In the [consent](https://www.w3.org/TR/audio-output/#privacy-consent) section:

> The default audio output device is always authorized.

That seems problematic unless there is a "null" output device. I often want all web pages to be unable to make sounds (I typically do that at the hardware level by inserting a blank jack into the headphone output, but that is suboptimal).

It looks like there should be an option for the user to **remove** consent from the default audio output device.

**Comment by youennf** [comment]
'The default audio output device is always authorised' is no longer in the latest draft I believe: https://w3c.github.io/mediacapture-output/. Instead the current wording is 'The specification adds no permission requirement to the default audio output device.'.

As of removing consent for the default audio output device, this is outside of the scope of the spec. This seems like something that should be offered by the browser directly.
 
It is true some pages might want to forbid iframes from playing audio but that seems like another request.

**Comment by guidou** [comment]
I agree with @youennf in that removing permission to play sound is outside the scope of the spec. There are already implementations of this. For example, Chrome allows muting a tab completely via UI and I do not see any need to change this spec to allow that.
Closing, but feel free to reopen if you think there is no consensus on this issue.
