### ISSUE TITLE
Rename HTMLMediaElement.setSinkId to a more readable name

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-output#92]
We are envisioning adding MediaDevices.selectAudioOutput/selectAudioOutputDevice and MediaDevices.setAudioOutput/setAudioOutputDevice.
We could consider updating HTMLMediaElement.setSinkId to HTMLMediaElement.setAudioOutput/setAudioOutputDevice

**Comment by abhijeetk** [comment]
Isn't it related to https://github.com/w3c/mediacapture-output/issues/112 ?

**Comment by dontcallmedom** [comment]
indeed, closing this one as a dup since #112 has some discussion already
